knp_paginator:



#    default_options:
#      page_name: page # nazwa zmiennej w adresie Url, np: ?page=1
#      sort_field_name: id
#      sort_direction_name: desc
#      distinct: true
 #     filter_field_name: filterField
#      filter_value_name: filterValue

    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'
